### ISSUE TITLE
TypeError during setup.py install

### ISSUE THREAD

**Issue by todi** [evgeni/bley#29]
Calling `python setup.py install` with python 3 leads to the following error:

```Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    (systemd_unit_path(), ['bley.service'])
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python3.6/distutils/command/install.py", line 557, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/install_data.py", line 60, in run
    dir = change_root(self.root, dir)
  File "/usr/lib/python3.6/distutils/util.py", line 149, in change_root
    return os.path.join(new_root, pathname[1:])
  File "/usr/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by evgeni** [comment]
#30 was merged, closing
